pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.parchmentmc.org' }
    }
    // https://github.com/CraftTweaker/CraftTweaker/blob/1.19/settings.gradle.kts#L22-L31
  //  resolutionStrategy {
  //      eachPlugin {
  //          if (requested.id.id == "org.spongepowered.mixin") {
  //              useModule("org.spongepowered:mixingradle:${requested.version}")
  //          }
  //      }
  //  }

}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}